version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dbCrudAnime
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: softcp
    volumes:
      - /home/darlei/Documents/volumes_docker
    ports:
      - "5432:5432"
    init: true