spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/softcp
    username: usuario
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true

server:
  address: localhost
  port: 8080


