
CREATE TABLE IF NOT EXISTS MANGA(
    ID UUID PRIMARY KEY NOT NULL,
    VOLUMES INTEGER NOT NULL,
    CHAPTERS INTEGER NOT NULL,
    STATUS VARCHAR(256) NOT NULL,
    SERIALIZATION VARCHAR(32) NOT NULL,
    AUTHORS VARCHAR(64) NOT NULL
);